### ISSUE TITLE
Take advantage of jti instead of PLAY_SESSION

### ISSUE THREAD

**Issue by MatteCarra** [playframework/play-scala-kalium-example#28]
I think that it is unnecessary to use play session, because you can use jti.
Then I would recommend to store only jtis that logged out, until they expire. 
This could save a lot of space in big projects.

**Comment by wsargent** [comment]
@MatteCarra I don't understand what "store only jtis that logged out" means.  Can you submit a PR?

**Comment by MatteCarra** [comment]
@wsargent It would be a token blacklist.
 I'm not familiar with scala.

**Comment by wsargent** [comment]
There isn't an expiration defined on the session, so you can't black list until the expiration date.
