### ISSUE TITLE
A note about Artery remote security

### ISSUE THREAD

**Issue by henrymana** [playframework/play-scala-kalium-example#46]
It would be great to add this note about remote security just in case anyone thinks the replicated caching" is secure out of the box and to make it explicit they need to handle network security.
 
http://doc.akka.io/docs/akka/2.5.4/scala/remoting-artery.html#remote-security

**Comment by wsargent** [comment]
This is already added in the session cache documentation:

```
 * Note that this doesn't serialize using protobuf and also isn't being sent over SSL,
 * so it's still not as secure as it could be.
```

https://github.com/playframework/play-scala-secure-session-example/blob/2.6.x/app/services/session/SessionCache.scala#L15

**Comment by wsargent** [comment]
BTW, using a database is perfectly fine for session information in 99% of cases: http://thebuild.com/blog/2015/10/30/dont-assume-postgresql-is-slow/
